### ISSUE TITLE
Call to undefined function format_json()

### ISSUE THREAD

**Issue by loganfranken** [ed-data/fafsa-api#10]
When running the project locally, I get the following error:

```
Fatal error: Call to undefined function format_json() on line 55
```

I see some utility methods out there with this signature (https://gist.github.com/GloryFish/1045396), but I don't think it's a built-in PHP function.

I'm wondering if the project is missing an include?

Either way, if this is just for JSON prettyprinting, then I think we can just remove the call to this function altogether; Chrome Dev Tools or [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) can handle the work of making it look nice for the end user.

**Comment by loganfranken** [comment]
(The end user being a developer or other curious person)

**Comment by kinlane** [comment]
Yeah, this was party of my legacy infrastructure, which obviously I didn't decouple well as I thought. Here it is, if you want to include. But as you said it is just to make it perty. ;-)

function format_json($json, $html = false, $tabspaces = null)
    {
        $tabcount = 0;
        $result = '';
        $inquote = false;
        $ignorenext = false;

        if ($html) {
            $tab = str_repeat("&nbsp;", ($tabspaces == null ? 4 : $tabspaces));
            $newline = "<br/>";
        } else {
            $tab = ($tabspaces == null ? "\t" : str_repeat(" ", $tabspaces));
            $newline = "\n";
        }

        for($i = 0; $i < strlen($json); $i++) {
            $char = $json[$i];

            if ($ignorenext) {
                $result .= $char;
                $ignorenext = false;
            } else {
                switch($char) {
                    case ':':
                        $result .= $char . (!$inquote ? " " : "");
                        break;
                    case '{':
                        if (!$inquote) {
                            $tabcount++;
                            $result .= $char . $newline . str_repeat($tab, $tabcount);
                        }
                        else {
                            $result .= $char;
                        }
                        break;
                    case '}':
                        if (!$inquote) {
                            $tabcount--;
                            $result = trim($result) . $newline . str_repeat($tab, $tabcount) . $char;
                        }
                        else {
                            $result .= $char;
                        }
                        break;
                    case ',':
                        if (!$inquote) {
                            $result .= $char . $newline . str_repeat($tab, $tabcount);
                        }
                        else {
                            $result .= $char;
                        }
                        break;
                    case '"':
                        $inquote = !$inquote;
                        $result .= $char;
                        break;
                    case '\\':
                        if ($inquote) $ignorenext = true;
                        $result .= $char;
                        break;
                    default:
                        $result .= $char;
                }
            }
        }

        return $result;
    }

**Comment by loganfranken** [comment]
Ahh, yeah, I'll go ahead and include it (I don't want to make too many structural changes to the codebase yet).
