### ISSUE TITLE
Is this working/possible?

### ISSUE THREAD

**Issue by logikinc** [ed-data/fafsa-api#6]
Hello, I was wondering if this was still possible or working?

**Comment by kinlane** [comment]
It was always a work in progress for department of education and white house, trying to jumpstart the conversation. It is not a functional FAFSA API to submit within the department, but was a functioning prototype to show what is possible. There is a long political road, one that in my opinion is fought best from outside in, to get Department of Education to integrate.

**Comment by kinlane** [comment]
Here there. We got some more funding to move this project forward. If you are interested in getting involved again, let us know.

**Comment by logikinc** [comment]
Yes, sorry, I was away. What did you have in mind by "getting involved"?

Thank you

**Comment by kinlane** [comment]
Hey there. This isn't a functional API at this point, it was just a prototype to convince the Dept of ed at several points to fund this internally. 

However we are moving forward now regardless of internal buy-in 100%. It needs to be done.

We have investment for some of the development to build a functional API, and portal to support the next wave of development.

At this point we don't need anything, except feedback on what is needed for next phase, so when we are done with next iteration, we have another roadmap ready for phase two.

**Comment by logikinc** [comment]
Just curious, is there an estimate, even a rough one, one when this would possibly be functional enough to start testing?

**Comment by kinlane** [comment]
Not yet no. We will publish roadmap to this project site as soon as ready.
