### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by loganfranken** [ed-data/fafsa-api#8]
I think there needs to be some developer documentation to assist new developers in getting up and running with the project (what dependencies are required, what needs to be created first, etc.).

I plan to create this while setting up the project for myself.

**Comment by kinlane** [comment]
Yes. Yes. and Yes. Something I intended but got sucked into doing behind the scenes RFI for department of education, which never went anywhere. Interesting to think about now...were they trying to distract me?

**Comment by loganfranken** [comment]
:)
